# Generated by Django 3.2.4 on 2021-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suchana', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techsuchana',
            old_name='uninotice',
            new_name='cybercrime',
        ),
        migrations.AddField(
            model_name='techsuchana',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
