# Generated by Django 3.2.4 on 2021-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suchana', '0002_auto_20210701_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsuchana',
            name='image1',
            field=models.ImageField(blank=True, upload_to='newspic'),
        ),
        migrations.AddField(
            model_name='techsuchana',
            name='image2',
            field=models.ImageField(blank=True, upload_to='newspic'),
        ),
    ]
