# Generated by Django 2.2 on 2022-12-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suchana', '0003_auto_20210723_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsuchana',
            name='displaylink',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='techsuchana',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
